export default {
    GET_AVAILABLE_DRIVERS:"GET_AVAILABLE_DRIVERS",
    GET_PENDING_BOOKINGS:"GET_PENDING_BOOKINGS",
    DRIVER_ACCEPTED_BOOKING:"DRIVER_ACCEPTED_BOOKING",
    DRIVER_REJECTED_BOOKING:"DRIVER_REJECTED_BOOKING"
};