export default {
    GET_AVAILABLE_DRIVERS:"GET_AVAILABLE_DRIVERS",
    GET_PENDING_BOOKINGS:"GET_PENDING_BOOKINGS",
    DRIVER_ACCEPTED_BOOKING:"DRIVER_ACCEPTED_BOOKING",
    DRIVER_REJECTED_BOOKING:"DRIVER_REJECTED_BOOKING",
    GET_DRIVER_LOCATION:"GET_DRIVER_LOCATION",
    DRIVER_ON_THE_WAY:"DRIVER_ON_THE_WAY",
    DRIVER_REGISTERED:"DRIVER_REGISTERED"
};