export default {
    GET_DISTANCE_FROM_CUSTOMER:"GET_DISTANCE_FROM_CUSTOMER",
    GET_DISTANCE_FROM_DESTINATION:"GET_DISTANCE_FROM_DESTINATION",
    GET_DRIVER_LATEST_LOCATION:"GET_DRIVER_LATEST_LOCATION",
    GET_CURRENT_BOOKING:"GET_CURRENT_BOOKING"
};