export default {
    GET_CURRENT_LOCATION:"GET_CURRENT_LOCATION",
    GET_INPUT:"GET_INPUT",
    SELECTED_SEARCH_TAB:"SELECTED_SEARCH_TAB",
    GET_ADDRESS_SUGGESTIONS:"GET_ADDRESS_SUGGESTIONS",
    GET_SELECTED_ADDRESS:"GET_SELECTED_ADDRESS",
    GET_DISTANCE_MATRIX:"GET_DISTANCE_MATRIX",
    GET_FARE:"GET_FARE",
    BOOK_CAR:"BOOK_CAR",
    GET_NEAR_BY_DRIVERS:"GET_NEAR_BY_DRIVERS"
};